langage: c
os: linux
dist: bionic
cache: false

compiler:
  - gcc
  - clang

os: linux

before_script:
  - autoreconf -vif

script: 
  - ./configure --enable-wall --enable-dwarfexample && make && make check
