name: freebsd_autotools CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    name: FreeBSD
    steps:
    - uses: actions/checkout@v2
    - name: FreeBSD VM
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        sync:  rsync
        copyback: false
        prepare: pkg install -y autoconf automake libtool pkgconf python3 bash gmake binutils pkgconf lzlib 
        run: |
          whereis bash
          ./autogen.sh
          ./configure
          make
          make check
