name: linux_autotools CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dos2unix
      run:  sudo apt-get install dos2unix
    - name: autoreconf
      run:  autoreconf -vif
    - name: configure
      run:  ./configure --enable-dwarfexample
    - name: make -j
      run:  make
    - name: make -j check
      run:  make check
    - name: make distcheck
      run:  make distcheck
