name: msys2_autotools CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      PYTHONIOENCODING: "utf-8"

    steps:
    - uses: actions/checkout@master
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: base-devel git autoconf automake libtool mingw-W64-x86_64-toolchain mingw-w64-x86_64-zlib
    - name: Configure
        run: autoreconf -vif && ./configure --disable-static --enable-shared --host=x86_64-pc-mingw32
    - name: Build
      run: make -j
    - name: Check
      run: make -j check
    -name: Distcheck
      run: make -j distcheck DISTCHECK_CONFIGURE_FLAGS="--disable-static --enable-shared --host=x86_64-pc-mingw32"
