name: macos_autotools CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: tools
      run:  |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install cmake ninja 
    - name: 
      run:  |
        mkdir builddir && cd builddir
        cmake -G ninja -DBUILD_DWARFEXAMPLE=ON ../CMakeLists.txt
        ninja
        ninja test
