name: cmake CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cmake
      run: |
        sudo apt-get -qq update
        sudo apt install build-essential cmake 
    - name: Build libdwarf
      run: |
        mkdir builddir && cd builddir
        cmake -DDO_TESTING=ON -DBUILD_DWARFEXAMPLE=ON ../CMakeLists.txt
        make
        ctest -R self
