name: freebsd_cmake

on:
  workflow_dispatch:

permissions: read-all

jobs:
  freebsd_cmake:
    name: FreeBSD using cmake
    uses: cross-platform-actions/action@v0.20.0
    with:
      operating_system: freebsd
      version:  '13.2'
      shell: bash
      prepare: |
        freebsd-version
        sudo pkg install -y python3 bash cmake ninja pkgconf
        sudo pkg install -y gmake binutils lzlib
      run: |
        mkdir builddir && cd builddir
        cmake -G Ninja -DBUILD_DWARFEXAMPLE=ON ../CMakeLists.txt
        ninja
        ninja test

