name: freebsd_cmake

on:
  workflow_dispatch:

permissions: read-all

jobs:
  freebsd_cmake:
    runs-on: macos-12
    name: FreeBSD
    steps:
    - uses: actions/checkout@v3
    - name: FreeBSD VM using cmake
      uses: cross-platform-actions/action@v0.20.0
      with:
        usesh: true
        sync:  rsync
        copyback: false
        prepare: pkg install -y python3 bash cmake ninja pkgconf gmake binutils lzlib
        operating_system: freebsd
        version:  '13.2'
        run: |
          freebsd-version
          mkdir builddir && cd builddir
          cmake -G Ninja -DBUILD_DWARFEXAMPLE=ON ../CMakeLists.txt
          ninja
          ninja test

