name: freebsd_cmake

on:
  workflow_dispatch:

permissions: read-all

jobs:
  freebsd_cmake:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name FreeBSD-with-cmake
        uses: cross-platform-action@v0.20.0
        with:
          operating_system: freebsd
          version:  '13.2'
          run: |
            uname -a
            freebsd-version
            echo $SHELL
            sudo pkg install -y python3 bash cmake ninja pkgconf
            sudo pkg install -y gmake binutils lzlib
            mkdir builddir && cd builddir
            cmake -G Ninja -DBUILD_DWARFEXAMPLE=ON ../CMakeLists.txt
            ninja
            ninja test

