name: freebsd_cmake

on:
  workflow_dispatch:

permissions: read-all

jobs:
  freebsd_cmake:
    runs-on: macos-12
    name: FreeBSD using cmake
    steps:
      uses: cross-platform-actions/action@v0.20.0
      with:
        operating_system: freebsd
        version:  '13.2'
        shell: bash
        run: |
          freebsd-version
          sudo pkg install -y python3 bash cmake ninja pkgconf
          sudo pkg install -y gmake binutils lzlib
          mkdir builddir && cd builddir
          cmake -G Ninja -DBUILD_DWARFEXAMPLE=ON ../CMakeLists.txt
          ninja
          ninja test

